language: node_js

node_js:
  - '10'

cache:
  yarn: true

env:
  NODE_ENV: 'release'

branches:
  only:
    - master

before_install:
  - npm i -g yarn

install:
  - yarn

script:
  - yarn test && yarn build && yarn build_example
